### ISSUE TITLE
TODO's

### ISSUE THREAD

**Issue by beevabeeva** [ohanoch/cgv_game#10]
# T O D O 's

## LEVEL 0

- [x] Make points part of alpha class
- [x] Remove ceiling wireframe from minimap
- [x] FIx buildings going below floor
- [x] Add comments to code: minimap stuff, container stuff, Pause/Piss
- [x] Remove animation checkbox and function
- [x] Add P key that makes avatar start/ stop peeing
- [x] Check if Detector.js is useful/needed
- [x] Make all functions cAmEl case
- [x] Add back full screen and F5 refresh browser defaults
- [x] Load js models 
- [x] Load JSON models (if necessary)
- [x] Movement of player with keyboard
- [x] Smooth keyboard multi keys
- [x] Camera return to default position after releasing left mouse button
- [x] Change camera to not go below floor
- [x] Object Inheritance (classes)
	- [x] alpha class
	- [x] map class
	- [x] power-ups class extends items
	- [x] items class
	- [x] collectibles class extends items
	- [x] other?
	- [x] review design of OOP
- [x] Collision:
	- [x] Die when you leave bounding box/walls
	- [x] Collide with laser-ceiling thing. (maybe won't have to use raycasting here, rather just check height and auto die if beyond limit/ respawn to default height in a legal position
	- [x] Collide with floor. (maybe won't have to use raycasting here, rather just check height and auto die if beyond limit/ respawn to default height in a legal position
	- [x] modify example to get basic collision between two objects
	- [x] When player crashes and has lives left, respawn from legal position nearest to crash site, if game-over have to start from scratch , loose all items
	- [x] When powerup collected, remove it from scene <(maybe with a fancy animation to signal to                             player that item was successfully collected - maybe done with SFX instead)> NO!
	- [x] apply collision to spawned blocks
        - [x] apply collision to pre-made buildings
	- [x] make power-up objects
- [x] Update alpha attributes on collisions (death, lives, powerups, points, etc)
- [x] Minimap
- [x] Win/Loose state (and notification/ transition to menu or something...)

## Level 0+
- [ ] make a cat that gives you 9 lives and you have to catch it and it runs around
- [ ] Add different views using keys
- [x] Shooting (maybe)
- [x] Show menu when pausing
- [x] Menu (using ray casting) * ASK RICHARD IF THIS IS SUFFICIENT TO GET ALL THE MARKS
- [x] Avatar animations (keyframing)
- [x] Avatar animation: turning animations
- [x] Texturing
- [x] Lighting (multiple lights)
- [x] Shading (wtf is this?)
- [x] Reflections
- [x] Shadows
## Level 0++
- [x] Colour Scheme
- [x] Dynamic skybox
- [x] Original model made in blender
- [x] Sound FX
- [x] Music
- [x] Refactor functions into JS files
- [ ] use some sort of require.js thing (Ask Nathan)
- [x] Clean lab9 (base) code
- [x] OOP, functions as much as possible,
- [x] Testing/Bug fixing
- [x] Restart

## Individual levels
- [x] Avi
- [x] Niambh
- [x] Or

**Comment by NiambhB** [comment]
hello
