### ISSUE TITLE
BETA TODO LIST (NO BULLSHIT!)

### ISSUE THREAD

**Issue by ohanoch** [ohanoch/cgv_game#29]
# BETA T O D O 's
- [ ] try catch for loaders 
- [ ] add an object with diffuse lighting
- [x] cube map on/off key
- [x] josh sucks shading
- [x] make death
- [x] make points
- [x] multiple lights 
- [x] make skybox dynamic
- [x] shadows
- [x] reflections
- [x] add collectibles to minimap
- [x] collectables = win state
- [x] make player crash when they hit the floor or the ceiling
- [x] basic menu
- [x] game can restart
- [x] Individual levels explanation
- [x] cleanup code
- [x] tilting when rotating

## Bonuses
- [x] spread out power ups and collectables
- [x] fine tune hyperperameters for beta
- [ ] star wars style lore
- [x] fix haha sound with html
- [x] remvoe wireframe in minimap and make camera and sphere higher
- [x] collectible markers need to disappear from the minimap when collectibles are collected
